select *
  , case when RANK_FALLOFF_PCT_OF_JOB_AMT <= 5 then TRUE else FALSE end as BRANCH_TOP5_FALLOFF_PCT_OF_JOB_AMT
from (
  select a.*, b.* except(DIVISION, BRANCH)
    , RANK() OVER(PARTITION BY a.DIVISION ORDER BY a.FALLOFF_PCT_OF_JOB_AMT DESC) as RANK_FALLOFF_PCT_OF_JOB_AMT
  from (
    select x.DATA_REFRESH_DATETIME
         , x.FSCL_YR_WK_KEY_VAL
         , loc.HDE_DIVISION_NM as DIVISION
         , loc.HDE_BRANCH_NM as BRANCH
         , sum(JOB_AMT) as JOB_AMT_SCHEDULED
         , COUNT(*) as JOB_COUNT_SCHEDULED
         , sum(JOB_AMT) - sum(JOB_AMT_INSTALLED) as JOB_AMT_FALL_OFF
         , COUNT(*) - SUM(JOB_COUNT_INSTALLED) as JOB_COUNT_FALL_OFF
         , SUM(JOB_AMT_CANCELED) AS JOB_AMT_CANCELED
         , SUM(JOB_COUNT_CANCELED) AS JOB_COUNT_CANCELED
         , SUM(JOB_AMT_RESCHEDULED) AS JOB_AMT_RESCHEDULED
         , SUM(JOB_COUNT_RESCHEDULED) AS JOB_COUNT_RESCHEDULED
         , SUM(JOB_AMT_AGED) AS JOB_AMT_AGED
         , SUM(JOB_COUNT_AGED) AS JOB_COUNT_AGED
         , SUM(JOB_AMT_UNSCHEDULED) AS JOB_AMT_UNSCHEDULED
         , SUM(JOB_COUNT_UNSCHEDULED) AS JOB_COUNT_UNSCHEDULED
         , SUM(JOB_AMT_INSTALLED) AS JOB_AMT_INSTALLED
         , SUM(JOB_COUNT_INSTALLED) AS JOB_COUNT_INSTALLED
         , SAFE_DIVIDE( SUM(JOB_AMT) - SUM(JOB_AMT_INSTALLED), SUM(JOB_AMT) ) AS FALLOFF_PCT_OF_JOB_AMT
         , SAFE_DIVIDE( COUNT(*) - SUM(JOB_COUNT_INSTALLED), COUNT(*) ) AS FALLOFF_PCT_OF_JOB_COUNT
    from `analytics-ahs-owned-thd.{REPORTING_DATASET}.HDE_FALLOFF_JOB_LVL` as x
    left join `pr-edw-views-thd.SVCS_MYSERVICESDRILL.LOC_HIER_OPS_MERCH` as loc
      on loc.LOC_NBR = x.STR_NBR
    where loc.HDE_SCN_FLG = 'N'
    group by 1,2,3,4
  ) as a
  left join (
    select DIVISION
         , BRANCH
         , SUM(JOB_COUNT) as HDIS_SCORECARD_JOB_COUNT
         , SUM(IR) as HDIS_SCORECARD_IR
    from `analytics-ahs-owned-thd.{STAGING_DATASET}.HDE_FALLOFF_HDIS_SCORECARD_METRICS_BRANCH_{RUN_DATE}`
    group by 1,2
  ) as b
    on b.DIVISION = a.DIVISION
    and b.BRANCH = a.BRANCH
)
