select a.*, b.* except(DIVISION, REGION)
from (
  select x.DATA_REFRESH_DATETIME
       , x.FSCL_YR_WK_KEY_VAL
       , loc.HDE_DIVISION_NM as DIVISION
       , loc.HDE_REGION_NM as REGION
       , SUM(JOB_AMT_CANCELED) AS JOB_AMT_CANCELED
       , SUM(JOB_COUNT_CANCELED) AS JOB_COUNT_CANCELED
       , SUM(JOB_AMT_RESCHEDULED) AS JOB_AMT_RESCHEDULED
       , SUM(JOB_COUNT_RESCHEDULED) AS JOB_COUNT_RESCHEDULED
       , SUM(JOB_AMT_AGED) AS JOB_AMT_AGED
       , SUM(JOB_COUNT_AGED) AS JOB_COUNT_AGED
       , SUM(JOB_AMT_UNSCHEDULED) AS JOB_AMT_UNSCHEDULED
       , SUM(JOB_COUNT_UNSCHEDULED) AS JOB_COUNT_UNSCHEDULED
       , SUM(JOB_AMT_INSTALLED) AS JOB_AMT_INSTALLED
       , SUM(JOB_COUNT_INSTALLED) AS JOB_COUNT_INSTALLED
       , SUM(JOB_AMT) as JOB_AMT_SCHEDULED
       , COUNT(*) as JOB_COUNT_SCHEDULED
       , SUM(JOB_AMT) - SUM(JOB_AMT_INSTALLED) AS JOB_AMT_FALL_OFF
       , COUNT(*) - SUM(JOB_COUNT_INSTALLED) AS JOB_COUNT_FALL_OFF
       , SAFE_DIVIDE( SUM(JOB_AMT) - SUM(JOB_AMT_INSTALLED), SUM(JOB_AMT) ) AS FALLOFF_PCT_OF_JOB_AMT
       , SAFE_DIVIDE( COUNT(*) - SUM(JOB_COUNT_INSTALLED), COUNT(*) ) AS FALLOFF_PCT_OF_JOB_COUNT
  from `analytics-ahs-owned-thd.{REPORTING_DATASET}.HDE_FALLOFF_JOB_LVL` as x
  left join `pr-edw-views-thd.SVCS_MYSERVICESDRILL.LOC_HIER_OPS_MERCH` as loc
    on loc.LOC_NBR = x.STR_NBR
  where loc.HDE_SCN_FLG = 'N'
  group by 1,2,3,4
) as a
left join (
  select DIVISION
       , REGION
       , SUM(JOB_COUNT) as HDIS_SCORECARD_JOB_COUNT
       , SUM(IR) as HDIS_SCORECARD_IR
  from `analytics-ahs-owned-thd.{STAGING_DATASET}.HDE_FALLOFF_HDIS_SCORECARD_METRICS_BRANCH_{RUN_DATE}`
  group by 1,2
) as b
  on b.DIVISION = a.DIVISION
  and b.REGION = a.REGION
