select a.*
from (
  select DIVISION
       , 'Division' as LOCATION_LEVEL
       , DIVISION as LOCATION
       , sum(HDIS_SCORECARD_IR) as HDIS_SCORECARD_IR
       , sum(HDIS_SCORECARD_JOB_COUNT) as HDIS_SCORECARD_JOB_COUNT
       , sum(JOB_AMT_SCHEDULED) as BOW_SCHEDULED
       , sum(JOB_COUNT_SCHEDULED) as BOW_SCHEDULED_JOBS
       , sum(JOB_AMT_CANCELED) as JOB_AMT_CANCELED
       , sum(JOB_COUNT_CANCELED) as JOB_COUNT_CANCELED
       , sum(JOB_AMT_RESCHEDULED) as JOB_AMT_RESCHEDULED
       , sum(JOB_COUNT_RESCHEDULED) as JOB_COUNT_RESCHEDULED
       , sum(JOB_AMT_UNSCHEDULED) as JOB_AMT_UNSCHEDULED
       , sum(JOB_COUNT_UNSCHEDULED) as JOB_COUNT_UNSCHEDULED
       , sum(JOB_AMT_AGED) as JOB_AMT_AGED
       , sum(JOB_COUNT_AGED) as JOB_COUNT_AGED
       , sum(JOB_AMT_SCHEDULED) - sum(JOB_AMT_INSTALLED) as JOB_AMT_FALL_OFF
       , SUM(JOB_COUNT_SCHEDULED) - SUM(JOB_COUNT_INSTALLED) as JOB_COUNT_FALL_OFF
       , sum(JOB_AMT_INSTALLED) as JOB_AMT_INSTALLED
       , sum(JOB_COUNT_INSTALLED) as JOB_COUNT_INSTALLED
       , SAFE_DIVIDE(sum(JOB_AMT_SCHEDULED) - sum(JOB_AMT_INSTALLED), sum(JOB_AMT_SCHEDULED)) as FALL_OFF_PCT_OF_JOB_AMT
  from `analytics-ahs-owned-thd.BSC.HDE_FALLOFF_BRANCH`
    group by 1,2,3

  union all

  select DIVISION
       , 'Branch' as LOCATION_LEVEL
       , BRANCH as LOCATION
       , sum(HDIS_SCORECARD_IR) as HDIS_SCORECARD_IR
       , sum(HDIS_SCORECARD_JOB_COUNT) as HDIS_SCORECARD_JOB_COUNT
       , sum(JOB_AMT_SCHEDULED) as BOW_SCHEDULED
       , sum(JOB_COUNT_SCHEDULED) as BOW_SCHEDULED_JOBS
       , sum(JOB_AMT_CANCELED) as JOB_AMT_CANCELED
       , sum(JOB_COUNT_CANCELED) as JOB_COUNT_CANCELED
       , sum(JOB_AMT_RESCHEDULED) as JOB_AMT_RESCHEDULED
       , sum(JOB_COUNT_RESCHEDULED) as JOB_COUNT_RESCHEDULED
       , sum(JOB_AMT_UNSCHEDULED) as JOB_AMT_UNSCHEDULED
       , sum(JOB_COUNT_UNSCHEDULED) as JOB_COUNT_UNSCHEDULED
       , sum(JOB_AMT_AGED) as JOB_AMT_AGED
       , sum(JOB_COUNT_AGED) as JOB_COUNT_AGED
       , sum(JOB_AMT_SCHEDULED) - sum(JOB_AMT_INSTALLED) as JOB_AMT_FALL_OFF
       , SUM(JOB_COUNT_SCHEDULED) - SUM(JOB_COUNT_INSTALLED) as JOB_COUNT_FALL_OFF
       , sum(JOB_AMT_INSTALLED) as JOB_AMT_INSTALLED
       , sum(JOB_COUNT_INSTALLED) as JOB_COUNT_INSTALLED
       , SAFE_DIVIDE(sum(JOB_AMT_SCHEDULED) - sum(JOB_AMT_INSTALLED), sum(JOB_AMT_SCHEDULED)) as FALL_OFF_PCT_OF_JOB_AMT
  from `analytics-ahs-owned-thd.BSC.HDE_FALLOFF_BRANCH`
  group by 1,2,3
) as a
left join (
  select division
       , SAFE_DIVIDE(sum(JOB_AMT_SCHEDULED) - sum(JOB_AMT_INSTALLED), sum(JOB_AMT_SCHEDULED)) as FALL_OFF_PCT_OF_JOB_AMT_DIVISION
  from `analytics-ahs-owned-thd.BSC.HDE_FALLOFF_BRANCH`
  group by 1
) as b
  on b.division = a.division
order by
  IF(a.LOCATION_LEVEL = 'Grand Total', 1, 0)
  , b.FALL_OFF_PCT_OF_JOB_AMT_DIVISION desc
  , IF(a.LOCATION_LEVEL = 'Division', 0, 1)
  , a.FALL_OFF_PCT_OF_JOB_AMT
